

services:
  farmapi:
    image: farmapi:latest
    depends_on:
      - "postgreDocker"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:adminaccess@postgreDocker:5432/farmer_db
      - SECRET_KEY=d58f5cf962eee2061
      - JWT_SECRET_KEY=df8e5a7462e5c
      - FLASK_ENV=production
    ports:
      - "5000:5000"

  postgreDocker:
    image: postgres
    environment:
      POSTGRES_PASSWORD: adminaccess
      POSTGRES_DB: farmer_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data


  nginx_custom:
    image: nginx_custom:latest
    depends_on:
      - farmapi
    ports:
      - "80:80"


volumes:
  pg-data:
