version: "3.8"
configs:
  nginx_conf:
    file: ./nginx.conf
services:
  farmapi:
    image: farmapi:latest
    depends_on:
      - "postgreDocker"
    # restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:adminaccess@postgreDocker:5432/farmer_db
      - SECRET_KEY=d58f5cf962eee2061
      - JWT_SECRET_KEY=df8e5a7462e5c
    networks:
      - app_network

  postgreDocker:
    image: postgres
    environment:
      POSTGRES_PASSWORD: adminaccess
      POSTGRES_DB: farmer_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx_custom:
    image: nginx_custom:latest
    depends_on:
      - farmapi
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  pg-data:

networks:
  app_network:
    driver: overlay
    
